from __future__ import annotations

from collections.abc import Iterable
from pathlib import Path

from .models import NetworkPoint


def write_s2p(path: str | Path, points: Iterable[NetworkPoint], comment: str | None = None) -> Path:
    output = Path(path)
    output.parent.mkdir(parents=True, exist_ok=True)

    rows = list(points)
    with output.open("w", encoding="ascii", newline="\n") as handle:
        handle.write("! Generated by hfss-vna-bridge\n")
        if comment:
            for line in comment.splitlines():
                handle.write(f"! {line}\n")
        handle.write("# Hz S RI R 50\n")
        for point in rows:
            handle.write(
                f"{point.freq_hz:.9g} "
                f"{point.s11.real:.9g} {point.s11.imag:.9g} "
                f"{point.s21.real:.9g} {point.s21.imag:.9g} "
                f"{point.s12.real:.9g} {point.s12.imag:.9g} "
                f"{point.s22.real:.9g} {point.s22.imag:.9g}\n"
            )
    return output

